---
- apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- apt_repository:
     repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
     state: present

# - debug: msg="{{ get_virtualbox_license_hash }}"
