---
- get_url:
    url: http://download.virtualbox.org/virtualbox/5.2.0/Oracle_VM_VirtualBox_Extension_Pack-5.2.0-118431.vbox-extpack
    dest: /tmp

- shell: " printf \"y\n\" | VBoxManage extpack install /tmp//Oracle_VM_VirtualBox_Extension_Pack-5.2.0-118431.vbox-extpack --replace"
  register: get_virtualbox_license_hash

- user:
    name: "{{ username }}"
    groups: docker,vboxusers
    append: yes
